## LORA

lora_data = {
    "sd15_loras": {
        "1. Hipoly 3D Model": [{'url': "https://civitai.com/api/download/models/112806?type=Model&format=SafeTensor", 'name': "hipoly3DModel_v20.safetensors"}],
        "2. Concept": [{'url': "https://civitai.com/api/download/models/167994?type=Model&format=SafeTensor", 'name': "concept_v1.safetensors"}],
        "3. ppussy by Remphanstar": [{'url': "https://huggingface.co/Remphanstar/Rojos/resolve/main/ppussy.safetensors", 'name': "ppussy.safetensors"}],
        "4. brothaman by maximstar00": [{'url': "https://huggingface.co/maximstar00/cute_pussy/resolve/main/brothaman.safetensors", 'name': "brothaman.safetensors"}],
        "5. Slime Girl": [{'url': "https://civitai.com/api/download/models/170310?type=Model&format=SafeTensor", 'name': "slimeGirl_v10.safetensors"}],
        "6. Thick Lines": [{'url': "https://civitai.com/api/download/models/58951?type=Model&format=SafeTensor", 'name': "thickLines_v1.safetensors"}],
        "7. Thin Lines": [{'url': "https://civitai.com/api/download/models/58906?type=Model&format=SafeTensor", 'name': "thinLines_v1.safetensors"}],
        "8. High Detail": [{'url': "https://civitai.com/api/download/models/283261?type=Model&format=SafeTensor", 'name': "highDetail_v1.safetensors"}],
        "9. LowRA": [{'url': "https://civitai.com/api/download/models/45127?type=Model&format=SafeTensor", 'name': "lowra_v1.safetensors"}],
        "10. 3D Render Style": [{'url': "https://civitai.com/api/download/models/63998?type=Model&format=SafeTensor", 'name': "3DRenderStyle_v1.safetensors"}],
        "11. Epi Noise Offset": [{'url': "https://civitai.com/api/download/models/174016?type=Model&format=SafeTensor", 'name': "epiNoiseoffset_v2.safetensors"}],
        "12. Clothing Adjuster": [{'url': "https://civitai.com/api/download/models/344345?type=Model&format=SafeTensor", 'name': "clothingAdjuster_v1.safetensors"}],
        "13. Eyes Wide": [{'url': "https://civitai.com/api/download/models/144437?type=Model&format=SafeTensor", 'name': "eyesWide_v1.safetensors"}],
        "14. Good Hands": [{'url': "https://civitai.com/api/download/models/50851?type=Model&format=SafeTensor", 'name': "goodHands_v1.safetensors"}],
        "15. Perfect Eyes": [{'url': "https://civitai.com/api/download/models/44430?type=Model&format=SafeTensor", 'name': "perfectEyes_v1.safetensors"}],
        "16. Detail Tweaker": [{'url': "https://civitai.com/api/download/models/20546?type=Model&format=SafeTensor&size=full&fp=fp16", 'name': "detailTweaker_v1.safetensors"}],
        "17. Beautiful Detailed Eyes": [{'url': "https://civitai.com/api/download/models/332880?type=Model&format=SafeTensor", 'name': "beautifulDetailedEyes_v1.safetensors"}],
        "18. Hair Detailer": [{'url': "https://civitai.com/api/download/models/169692?type=Model&format=SafeTensor", 'name': "hairDetailer_v1.safetensors"}],
        "19. Breast In Class": [{'url': "https://civitai.com/api/download/models/110260?type=Model&format=SafeTensor", 'name': "breastinclass_v1.safetensors"}],
    },
    "sdxl_loras": {
        "1. Nudify XL": [{'url': "https://civitai.com/api/download/models/177674?type=Model&format=SafeTensor", 'name': "nudify-xl.safetensors"}],
        "2. Perfect Eyes XL": [{'url': "https://civitai.com/api/download/models/1030934?type=Model&format=SafeTensor", 'name': "perfectEyesXl_v1.safetensors"}],
        "3. Good Hands XL": [{'url': "https://civitai.com/api/download/models/859154?type=Model&format=SafeTensor", 'name': "goodHandsXl_v1.safetensors"}],
        "4. Clothing Adjuster XL": [{'url': "https://civitai.com/api/download/models/393888?type=Model&format=SafeTensor", 'name': "clothingAdjusterXl_v1.safetensors"}],
        "5. Breast In Class XL": [{'url': "https://civitai.com/api/download/models/1567868?type=Model&format=SafeTensor", 'name': "breastInClassXl_v1.safetensors"}],
        "6. Thick Lines XL": [{'url': "https://civitai.com/api/download/models/518802?type=Model&format=SafeTensor", 'name': "thickLinesXl_v1.safetensors"}],
        "7. Slime Girl XL": [{'url': "https://civitai.com/api/download/models/802232?type=Model&format=SafeTensor", 'name': "slimeGirlXl_v1.safetensors"}],
        "8. Hair Detailer XL": [{'url': "https://civitai.com/api/download/models/1604857?type=Model&format=SafeTensor", 'name': "hairDetailerXl_v1.safetensors"}],
        "9. High Detail XL": [{'url': "https://civitai.com/api/download/models/686514?type=Model&format=SafeTensor", 'name': "highDetailXl_v1.safetensors"}],
        "10. Epi Noise Offset XL": [{'url': "https://civitai.com/api/download/models/160240?type=Model&format=SafeTensor", 'name': "epiNoiseoffsetXl_v1.safetensors"}],
        "11. LowRA XL": [{'url': "https://civitai.com/api/download/models/427792?type=Model&format=SafeTensor", 'name': "lowraXl_v1.safetensors"}],
        "12. 3D Render Style XL": [{'url': "https://civitai.com/api/download/models/624818?type=Model&format=SafeTensor", 'name': "3DRenderStyleXl_v1.safetensors"}],
        "13. Thin Lines XL": [{'url': "https://civitai.com/api/download/models/567342?type=Model&format=SafeTensor", 'name': "thinLinesXl_v1.safetensors"}],
        "14. Eyes Wide XL": [{'url': "https://civitai.com/api/download/models/478142?type=Model&format=SafeTensor", 'name': "eyesWideXl_v1.safetensors"}],
        "15. Beautiful Detailed Eyes XL": [{'url': "https://civitai.com/api/download/models/1627770?type=Model&format=SafeTensor", 'name': "beautifulDetailedEyesXl_v1.safetensors"}],
        "16. Concept XL": [{'url': "https://civitai.com/api/download/models/717403?type=Model&format=SafeTensor", 'name': "conceptXl_v1.safetensors"}],
    }
}
