# CORRECTED LORA DATA SCRIPT

lora_data = {
    "sd15_loras": {
        "female masturbation concepts - v2-LyCORIS-LoCon": [{"url": "https://civitai.com/api/download/models/50851", "name": "concept-female_masturbation-v2.safetensors"}],
        "brothaman": [{"url": "https://huggingface.co/maximstar00/cute_pussy/resolve/main/brothaman.safetensors", "name": "brothaman.safetensors"}],
        "Female masturbation - mastv1": [{"url": "https://civitai.com/api/download/models/44430", "name": "mastv1.safetensors"}],
        "POV yuri cunnilingus - v1": [{"url": "https://civitai.com/api/download/models/58906", "name": "qqq-cunnilingus_pov-v1.safetensors"}],
        "Cute Pussy  - v2.0": [{"url": "https://civitai.com/api/download/models/112806", "name": "CutePussyVer2S.safetensors"}],
        "PornMaster-\u81ea\u62cd\u3001\u7a7f\u8863\u670d\u81ea\u6170\u3001\u88f8\u4f53\u81ea\u6170\u3001\u900f\u89c6\u3001\u9ad8\u6f6e\u8138& Selfie\u3001clothed masturbation\u3001naked masturbation\u3001see-through \u3001orgasm - V2-LYCORIS": [{"url": "https://civitai.com/api/download/models/344345", "name": "clothed masturbation_V2.safetensors"}],
        "Female masturbation - v0.5": [{"url": "https://civitai.com/api/download/models/174016", "name": "female_masturbation_v0.5.safetensors"}],
        "Female Masturbation [Boob Fondling and Fingering] - v1": [{"url": "https://civitai.com/api/download/models/20546", "name": "masturbation-v1.safetensors"}],
        "PornMaster-Pro \u8272\u60c5\u5927\u5e08 - FULL-V4-inpainting - FULL-V4-inpainting": [{"url": "https://civitai.com/api/download/models/102709", "name": "pornmasterProFULLV4_fullV4-inpainting.safetensors"}],
        "Hands Down Clothes - v1.0": [{"url": "https://civitai.com/api/download/models/144437", "name": "hand-down-clothes.safetensors"}],
        "yuri cunnilingus - lora - v1.0": [{"url": "https://civitai.com/api/download/models/283261", "name": "yuri_cunnilingus_v1.safetensors"}],
        "Sexy Catholic school uniform |anime+realistic| - v1.0": [{"url": "https://civitai.com/api/download/models/110260", "name": "CatholicSchoolUniformDogu.safetensors"}],
        "Hand in panties - v0.82": [{"url": "https://civitai.com/api/download/models/170310", "name": "hand_in_panties_v0.82.safetensors"}],
        "ppussy": [{"url": "https://huggingface.co/Remphanstar/Rojos/resolve/main/ppussy.safetensors", "name": "ppussy.safetensors"}],
        "Sexy School Uniform | olaz - v1": [{"url": "https://civitai.com/api/download/models/169692", "name": "sexyschooluniformv1.safetensors"}],
        "Labiaplasty (Innie Pussy Adjuster) [SD1.5 + SDXL] - v2.0": [{"url": "https://civitai.com/api/download/models/167994", "name": "m99_labiaplasty_pussy_2.safetensors"}],
        "School Dress Collection By Stable Yogi - SF_School_Dress": [{"url": "https://civitai.com/api/download/models/332880", "name": "SF_School_Dress_By_Stable_Yogi.safetensors"}],
        "Panties pulled aside fuck | Sex Lora 011 | Perfect - v1.0": [{"url": "https://civitai.com/api/download/models/63998", "name": "panties_pulled_aside_fuck.v1.0.safetensors"}],
        "yuri cunnilingus - v4": [{"url": "https://civitai.com/api/download/models/58951", "name": "qqq-yuri-cunnilingus-v4.safetensors"}],
        "Panties to side LoRA - v2": [{"url": "https://civitai.com/api/download/models/45127", "name": "PantiesToSide-v2.safetensors"}],
    },
    "sdxl_loras": {
        "BT Lowering Pants - Pony v1": [{"url": "https://civitai.com/api/download/models/393888", "name": "BT_Lowering_Pants_Pony.safetensors"}],
        "Lesbian fingering - v1.0": [{"url": "https://civitai.com/api/download/models/1030934", "name": "Lesbian_fingering.safetensors"}],
        "Yuri Mutual Masturbation - v1.0-XL": [{"url": "https://civitai.com/api/download/models/567342", "name": "Yuri Mutual Masturbation.safetensors"}],
        "Real Pussy - Cameltoe - v3 XL": [{"url": "https://civitai.com/api/download/models/802232", "name": "Pussy_Cameltoe_v3_XL.safetensors"}],
        "Striped Micro Lingerie PONY XL - v2.0": [{"url": "https://civitai.com/api/download/models/518802", "name": "hud_str_ling_v2_XLP.safetensors"}],
        "Nudify XL: Better Bodies - v1 Lite": [{"url": "https://civitai.com/api/download/models/177674", "name": "nudify_xl_lite.safetensors"}],
        "Fingering Under Clothes/Implied Masturbation | Concept LoRA | SDXL Pony - V1": [{"url": "https://civitai.com/api/download/models/427792", "name": "Lunas-Implied-Fingering-SDXL-A1.safetensors"}],
        "NSFW POV All In One SDXL (Realistic/Anime/WD14 - 74MB Version Available) - v1.0 (Full - Recommended)": [{"url": "https://civitai.com/api/download/models/160240", "name": "NsfwPovAllInOneLoraSdxl-000009.safetensors"}],
        "Masturbating Under Panties - v1.0-Pony": [{"url": "https://civitai.com/api/download/models/624818", "name": "MASTURBATING UNDER PANTIES.safetensors"}],
        "Multiple XL Sliders - Age, weight, Hands, etc - age_pony": [{"url": "https://civitai.com/api/download/models/686514", "name": "agepony8.pt"}],
        "\u30af\u30ed\u30c3\u30c1\u305a\u3089\u3057/panties aside(XL,Pony) - v2.0 pony": [{"url": "https://civitai.com/api/download/models/1567868", "name": "panty aside_pony_V2.0.safetensors"}],
        "School Swimsuit and Kneehighs / \u30b9\u30af\u6c34\u30cb\u30fc\u30bd - XLv1.0": [{"url": "https://civitai.com/api/download/models/478142", "name": "school swimsuit kneehigh XL-v1.safetensors"}],
        "LEAKCORE (LEAKED NUDES STYLE, Realism, Amateur) - v1.0 (LUSTIFY)": [{"url": "https://civitai.com/api/download/models/1627770", "name": "leaked_nudes_style_v1_fixed.safetensors"}],
        "Pony Amateur \u2728 - Standard (V2)": [{"url": "https://civitai.com/api/download/models/717403", "name": "zy_AmateurStyle_v2.safetensors"}],
        "Lesbian pussy licking - v1.0": [{"url": "https://civitai.com/api/download/models/859154", "name": "Lesbian_pussy_licking.safetensors"}],
        "Real Pussy - Peach - Rear v2 XL": [{"url": "https://civitai.com/api/download/models/1604857", "name": "Pussy_Peach_Rear_v2_XL.safetensors"}],
    }
}
